version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    networks:
      - my_network

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build:
      context: ./web
    ports:
      - "8081:80"
    networks:
      - my_network

networks:
  my_network:

volumes:
  jenkins_home:

